version: '3.8'

services:
  users-db:
    image: postgres:latest
    environment:
      POSTGRES_HOST: users-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    volumes:
      - users-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  comments-db:
    image: postgres:latest
    environment:
      POSTGRES_HOST: comments-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: comments_db
    volumes:
      - comments-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Перенаправляем на другой порт для комментариев

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - users-db
      - comments-db
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    environment:
      USERS_DB_URL: "postgres://user:password@users-db:5432/users_db"
      COMMENTS_DB_URL: "postgres://user:password@comments-db:5432/comments_db"

volumes:
  users-db-data:
  comments-db-data:
